import {displayVerticalCenter} from "../../core/style/constant";

const style = (theme) => ({
    container: {
        color: theme.palette.error.main,
        padding: 20,
        borderRadius: 3,
        width: "100%",
        justifyContent: "center",
        display: "flex",
        animationName: "$slideRight",
        animationDuration: "0.3s",
        height: "100%",
        alignItems: "center",
    },
    loaderScreen: {
        zIndex: 10000,
        position: "fixed",
        top: 0,
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        width: "100%",
        height: "100%",
        background: theme.palette.primary.main,
        animationName: "$opacityReduce",
        animationDuration: "1s",
        opacity: 0,
        pointerEvents: "none",
    },
    "@keyframes opacityReduce": {
        "0%": {opacity: 1},
        "90%": {opacity: 1},
        "100%": {opacity: 0},
    },
    loader: {
        width: 48,
        height: 48,
        borderTop: `2px solid ${theme.palette.primary.loaderColor}`,
        borderLeft: `2px solid ${theme.palette.primary.loaderColor}`,
        borderRight: `2px solid ${theme.palette.primary.loaderColor}`,
        borderBottom: "3px solid transparent !important",
        borderRadius: "50%",
        position: "relative",
        animation: "spin 1s linear infinite",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
    },
    inner: {
        width: 34,
        height: 34,
        borderBottom: "3px solid transparent !important",
        borderLeft: "3px solid transparent !important",
        borderRight: "3px solid transparent !important",
        borderTop: `2px solid ${theme.palette.primary.loaderColor}`,
        borderRadius: "50%",
        animation: "spinInner 1s linear infinite",
    },
    "@keyframes slideRight": {
        "0%": {opacity: 0},
        "50%%": {opacity: 0},
        "100%": {opacity: 1},
    },
    loaderSmall: {
        width: 20,
        height: 20,
        margin: 0,
        display: "inline-block",
        animation: "openLoader 3s linear",
        animationName: "$openLoader",
        animationDuration: "0.2s",
    },
    "@keyframes openLoader": {
        "0%": {width: 0},
        "100%": {width: 20},
    },
    absolute: {
        position: "absolute",
        height: "100%",
        width: "100%",
        background: theme.palette.background.default,
        top: 0,
        left: 0,
        opacity: 0.5,
        animationName: "$openAbsolute",
        animationDuration: "1s",
        zIndex: 1,
    },
    "@keyframes openAbsolute": {
        from: {opacity: 0},
        to: {opacity: 0.5},
    },
    layout: {
        position: "relative",
        height: "100%",
        width: "100%",
    },
    options: {
        ...displayVerticalCenter,
    },
    optionItem: {
        margin: "0 5px",
        padding: 4,
        height: 32,
        borderRadius: 6,
        transition: "0.2s",
        cursor: "pointer",
        minWidth: 50,
        ...displayVerticalCenter,
        "&:hover": {
            backgroundColor: `${theme.palette.white.main}2f`,
        },
    },
    sideOptions: {
        marginRight: 15,
        ...displayVerticalCenter,
    },
    body: {
        position: "relative",
        height: "100%",
    },
    skeleton: {
        backgroundColor: "rgb(255 255 255 / 11%)",
    },
});

export default style;
